### ISSUE TITLE
Removing devices from HA registry fails

### ISSUE THREAD

**Issue by bcutter** [gluap/pyduofern-hacs#44]
Tried the delete feature of https://github.com/gluap/pyduofern-hacs/releases/tag/v0.5.11 with my two ghost devices (following up on #36):

![grafik](https://github.com/gluap/pyduofern-hacs/assets/13799156/935f1655-790a-439c-8709-06e40917be60)

After deletion, nothing happens. Device stays in HA registry.

Getting two issues in HA log (please note: tried deleting one / the same device twice):

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/duofern/__init__.py:58
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:53:04 (2 occurrences)
Last logged: 16:55:11

[545929788096] Error handling message: Unknown error (unknown_error) %username% from xxx.xxx.xxx.xxx (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
[545932705072] Error handling message: Unknown error (unknown_error) %username% from xxx.xxx.xxx.xxx (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
Traceback (most recent call last):
  File "/config/custom_components/duofern/__init__.py", line 54, in async_remove_config_entry_device
    del (stick.duofern_parser.modules["by_code"][device_entry.name])
KeyError: '416415'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/config/device_registry.py", line 131, in websocket_remove_config_entry_from_device
    if not await component.async_remove_config_entry_device(
  File "/config/custom_components/duofern/__init__.py", line 58, in async_remove_config_entry_device
    logging.warning(device_entry.__dict__)
AttributeError: 'DeviceEntry' object has no attribute '__dict__'
```

and

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: root
Source: custom_components/duofern/__init__.py:57
Integration: Duofern control (documentation, issues)
First occurred: 16:53:04 (2 occurrences)
Last logged: 16:55:11

DeviceEntry(area_id=None, config_entries={'6fbbda39ef703642a9c032480f269e08'}, configuration_url=None, connections=set(), disabled_by=<DeviceEntryDisabler.USER: 'user'>, entry_type=None, hw_version=None, id='61907f529c228e7a1ac2ac1a8683c48b', identifiers={('duofern', '416415')}, manufacturer='Rademacher', model=None, name_by_user='zzzOLD_Non-Existing-NeverExisted-DeleteMe', name='416415', suggested_area=None, sw_version=None, via_device_id=None, is_new=False)
```

Update:
- same for the other ghost device
- also tried to enable devices prior to deleting them, same result

**Comment by gluap** [comment]
Ah I see,
this must have been a device that was already removed from duofern config (by means of clean_config), I had none of those so didn't test that. Hope it works with 0.5.13

**Comment by bcutter** [comment]
Yes, v0.5.13 looks much better:

- UI ✅
![grafik](https://github.com/gluap/pyduofern-hacs/assets/13799156/dd90d3ea-18fa-46d4-b41b-e24f3bc88268)

- `duofern.json` untouched ✅

- `core.device_registry` (and `core.entity_registry`): device (and entities) removed ✅

Summary: solved.

Thank you for your quick support on this. Happy new year! 🎉🚀
