### ISSUE TITLE
duofern Platform does not load anymore after update of HA to 2022.2.6

### ISSUE THREAD

**Issue by Basti-Fantasti** [gluap/pyduofern-hacs#16]
Hi there and thanks for your continues development!

Today I've updated my HA to the latest 2022.2.6 and the duofern component just could not be loaded any more.

Here's the log:

````
 Logger: homeassistant.setup
Source: setup.py:289
First occurred: 12. Februar 2022, 14:20:25 (2 occurrences)
Last logged: 12. Februar 2022, 14:20:25

    Unable to prepare setup for platform duofern.cover: Platform not found (cannot import name 'CoverDevice' from 'homeassistant.components.cover' (/usr/src/homeassistant/homeassistant/components/cover/__init__.py)).
    Unable to prepare setup for platform duofern.light: Platform not found (cannot import name 'Light' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)).

````

I'm not sure why it tries to load the component from the default components path instead of the custom_components? 
Maybe a breaking change inside HASSIO or the latest HA?

Follow up warnings are then e.g.:

````

Logger: homeassistant.helpers.service
Source: helpers/service.py:130
First occurred: 12. Februar 2022, 20:30:00 (3 occurrences)
Last logged: 08:10:00

Unable to find referenced entities cover.404eb1
Unable to find referenced entities cover.404ea8

````

Is anyone else facing this problem?

Best regards
Bastian

**Comment by Basti-Fantasti** [comment]
Seems to work with the 0.2 release of the duofern lib. 

Sorry I was still on 0.0.1 ...

**Comment by gluap** [comment]
Great to hear you figered it out so quickly!
